<a href="https://colab.research.google.com/github/yashc73080/CS462-Deep-Learning/blob/main/Recitation1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

PyTorch Tensor matrix/vector
- Optimized for GPU calculations

In [1]:
import torch

In [2]:
a = torch.tensor([1,2,3])
print(a)

tensor([1, 2, 3])


In [4]:
b = torch.tensor([[1,2,3],[4,5,6]])
print(b)

tensor([[1, 2, 3],
        [4, 5, 6]])


In [6]:
b.shape

torch.Size([2, 3])

In [8]:
c = torch.arange(0,30)
print(c)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])


In [9]:
d = torch.randn((2,3)) # size of tensor for normal distribution
print(d)

tensor([[-0.7518, -0.7077,  0.6965],
        [-0.9539,  1.1146, -1.3988]])


In [10]:
# Tensor with shape (2,3,4)
e = torch.randn((2,3,4))
print(e)

tensor([[[ 0.9170, -1.4527, -1.2824, -0.0772],
         [-0.5918,  0.7940,  0.2832,  0.0675],
         [-1.4702, -0.1856, -0.7124,  0.9672]],

        [[ 0.3444,  1.1821, -1.5106,  0.2963],
         [-1.2580, -0.1961,  0.7597, -1.0425],
         [-2.0623, -0.1278, -2.0668, -1.1248]]])


In [12]:
# Tensor with shape (2,3,4) with numbers from 1 to 24
f = torch.arange(1,25).reshape(2,3,4)
print(f)

tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],

        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]])


In [14]:
# Add 1 to every item in tensor -> broadcast
c + 1

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [17]:
a = torch.arange(0,20)
a + c

RuntimeError: The size of tensor a (20) must match the size of tensor b (30) at non-singleton dimension 0

In [18]:
a * 2

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38])

In [20]:
# Element-wise multiplication
a = torch.arange(0,20)
b = torch.arange(0,20)
a * b

tensor([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
        196, 225, 256, 289, 324, 361])

In [25]:
# Matrix multiplication
a = torch.randn((3,2))
b = torch.randn((3,2))
print(a)
print(b)
print(b.T) # Transpose to make the dimensions match
a @ b.T

tensor([[-0.0069, -0.7525],
        [-0.9406, -1.1044],
        [ 0.5956,  0.9261]])
tensor([[-1.2497,  2.4520],
        [-0.1143, -0.1825],
        [-0.2477,  0.4353]])
tensor([[-1.2497, -0.1143, -0.2477],
        [ 2.4520, -0.1825,  0.4353]])


tensor([[-1.8365,  0.1381, -0.3259],
        [-1.5324,  0.3091, -0.2477],
        [ 1.5265, -0.2371,  0.2556]])

In [26]:
# Indexing and slicing

a = torch.randn((1000, 3, 100, 100)) # ex: 1000 images, 3 channels, 100x100 pixels each
a[0, 0, 0, 0] # First image, R channel, top left corner

tensor(0.0422)

In [28]:
a[:10, :, 0, 0] # top left corner from top 10 images (all channels for each)

tensor([[ 0.0422,  0.9588, -0.4307],
        [-1.3289, -0.3056, -0.1331],
        [-1.0170, -0.3256, -1.3023],
        [ 1.3179, -0.8232,  0.2668],
        [ 0.7657, -1.0930,  0.1041],
        [ 0.1072, -0.0137,  0.4024],
        [ 2.4789,  1.2166, -0.3714],
        [ 0.6114, -0.3635,  0.5578],
        [-1.7836,  0.2323, -0.0912],
        [ 2.0166,  1.4943, -0.5813]])

In [29]:
a[:10, :, 0, 0].shape

torch.Size([10, 3])

In [31]:
a[10:, 0, :10, :10] # R channel for last 10 images, top left 100 pixels

tensor([[[-8.8176e-01,  6.0470e-01, -4.3271e-01,  ...,  2.7678e-01,
          -3.4548e-01,  1.0405e+00],
         [-4.0550e-02,  7.0470e-01,  1.3501e+00,  ...,  2.8509e-01,
          -4.0627e-01,  6.4305e-01],
         [-1.3980e+00,  2.1364e-02, -3.1718e-01,  ..., -7.0138e-02,
           7.4459e-01,  6.4488e-01],
         ...,
         [-6.5099e-01, -1.0479e+00,  5.8310e-02,  ...,  5.7139e-01,
           9.3632e-01, -3.2882e-01],
         [-3.1079e-01, -2.2597e+00,  3.4252e-01,  ...,  4.8703e-01,
          -9.5247e-01,  9.2335e-01],
         [-4.0454e-01,  1.0642e+00,  7.9699e-01,  ...,  7.4054e-01,
           2.9681e-01,  4.0485e-01]],

        [[-5.6830e-01,  9.1479e-03,  4.2268e-01,  ..., -7.3401e-01,
          -3.7336e-01,  1.1018e+00],
         [-4.9409e-02,  1.4499e+00,  4.2208e-01,  ..., -6.5796e-01,
          -5.8171e-01,  3.0801e-01],
         [-1.3307e-01,  9.6443e-01,  5.1890e-01,  ..., -4.3230e-02,
           1.0201e+00,  2.7380e-01],
         ...,
         [-1.2499e+00,  2

In [34]:
# Want to change the images to start with images, put channel at the end
b = a.permute((0, 2, 3, 1)) # original dim at id 0 stays, original dim of 1 moves to the end, etc
b

tensor([[[[ 0.0422,  0.9588, -0.4307],
          [ 0.5227,  0.1866, -0.0119],
          [-0.0680, -1.0583,  0.3845],
          ...,
          [ 2.1457,  1.0089, -0.0426],
          [-0.1680, -0.0498, -0.6672],
          [ 0.9802, -0.2156,  0.8862]],

         [[ 1.5902, -0.5481, -0.9675],
          [-0.1029, -0.1653, -2.1248],
          [ 0.8208,  1.5560,  0.4591],
          ...,
          [-0.5471,  1.0482,  0.7164],
          [-0.6042,  1.7971, -2.3018],
          [ 0.4201, -0.0218, -0.9696]],

         [[ 0.6920,  0.6740, -0.7557],
          [-0.5998, -1.5042, -0.1868],
          [-0.5206, -1.0715,  0.1111],
          ...,
          [-0.6835, -1.2101, -1.2234],
          [-0.6272, -1.1960,  0.1834],
          [-1.5783, -1.1087, -1.3663]],

         ...,

         [[ 0.6950, -1.3046, -1.1658],
          [-0.2649,  1.4289, -0.1451],
          [ 0.6518,  1.1243,  0.0066],
          ...,
          [ 0.2218, -1.4262, -0.7394],
          [ 0.1861, -0.8846, -1.0452],
          [-1.4017, -0

In [35]:
b.shape

torch.Size([1000, 100, 100, 3])

In [36]:
c = a.transpose(1,3)
c.shape

torch.Size([1000, 100, 100, 3])